### ISSUE TITLE
Implement more functions

### ISSUE THREAD

**Issue by xxczaki** [elcalc/elcalc#12]
Besides of basic functions, like addition, subtraction, we should have modulus (%), nth root (√), square (x2) & more.

**Comment by AadhithyanBalaji** [comment]
Added Modulus and square and merged with master

**Comment by xxczaki** [comment]
@AadhithyanBalaji Can you submit a Pull Request, please?

**Comment by audreylopes** [comment]
I can try to implement nth root.

**Comment by xxczaki** [comment]
@audreylopes Good luck 😀

**Comment by ItamarShDev** [comment]
is anything is left for me?

**Comment by xxczaki** [comment]
@ItamarShDev You can try to implement modulus & square, since @AadhithyanBalaji didn’t submit a PR yet. Check out his fork of elcalc ;) Maybe you can improve something :D

**Comment by xxczaki** [comment]
https://github.com/elcalc/elcalc/commit/a5b910584eed37b56901a5dafa527123329b4c5b
