### ISSUE TITLE
Keyboard on linux

### ISSUE THREAD

**Issue by liberodark** [elcalc/elcalc#6]
**Desktop (please complete the following information):**
 - OS: [Manjaro XFCE]
 - elcalc version: [4.0.9]

**Describe the bug**
The keyboard not work great on linux numers not work - or + not work just * and / and enter work.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xxczaki** [comment]
Hi, have you tried typing these symbols with Shift, for example:
<kbd>Shift</kbd> + <kbd>+</kbd>
or
<kbd>Shift</kbd> + <kbd>-</kbd>

**Comment by liberodark** [comment]
work with shift just 8 = x for what ?
im on French keyboard
But have number lock on keyboard and numers not work :(

**Comment by xxczaki** [comment]
Sorry, but I don't understand, please provide me with a more succinct description of your problem. Are you using numpad or just the numbers on keyboard (the ones above the QWERTY keys)?

Also, check out the table below:

| Key | Description |
| ------:| -----------:|
| <kbd>1,2,3,4,5,6,7,8,9,0</kbd> | Type numbers |
| <kbd>Shift</kbd> + <kbd>+,-,/,*</kbd> | Type symbols |
| <kbd>Enter</kbd> or <kbd>Return</kbd> | Evaluate equation |
| <kbd>Backspace</kbd> | Clear calculator output |

**Comment by liberodark** [comment]
This not work : https://st.depositphotos.com/1004137/4718/i/950/depositphotos_47184029-stock-photo-number-pad.jpg

**Comment by xxczaki** [comment]
@liberodark 
Ok, so numpad is not working. Have you turned it on? Are these numbers working?

    ⬇️⬇️⬇️ ⬇️⬇️⬇️ ⬇️⬇️⬇️
![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Belgian_keyboard_layout.png/500px-Belgian_keyboard_layout.png)

**Comment by liberodark** [comment]
Yes is on no numer work on numpad

**Comment by xxczaki** [comment]
ok, I probably know where the problem is, will try to fix it soon 😄 Thanks for your cooperation!

**Comment by xxczaki** [comment]
@liberodark Can you test this `.AppImage` on your Linux Machine? Everything should be working now 😄 [https://we.tl/ppXmiuw99p](https://we.tl/ppXmiuw99p)

**Comment by liberodark** [comment]
Have try and the result is : abcdefghi÷+ for 123456789/*-+

**Comment by xxczaki** [comment]
@liberodark soooo... are the numbers & symbols (+ - * /) working?

**Comment by xxczaki** [comment]
@liberodark never mind, I've just tested it and it still doesn't work, going to do another fix.

**Comment by xxczaki** [comment]
@liberodark Ok, check out the latest release: https://github.com/elcalc/elcalc/releases/tag/5.0-beta.1

**Comment by liberodark** [comment]
Is better keyboard work but no need shift !
But numpad /*-+ work but numbers not work.

**Comment by xxczaki** [comment]
@liberodark ok, please try the new beta 2 release, which should finally fix the problem! 😄
https://github.com/elcalc/elcalc/releases/tag/5.0-beta.2

**Comment by xxczaki** [comment]
@liberodark Also, I can confirm that something is wrong with the <kbd>-</kbd> key.

**Comment by liberodark** [comment]
Hi,

Beta 1 work better than beta 2 numpad is not work same for beta 1 and for beta 2 * not work

**Comment by xxczaki** [comment]
@liberodark ok, I will try to do something in beta.3. Can you go to this site (http://keycode.info/), click the key on Numpad, that doesn't work and paste this key's code here? 

Also, a short recording of the screen would be very helpful 👍

**Comment by xxczaki** [comment]
@liberodark please note that you don't need to use shift!

**Comment by xxczaki** [comment]
I'm going to close this issue, if it still won't work, let me know.

**Comment by xxczaki** [comment]
Update - numpad is not working 😢Gonna do a quick fix in rc1.

**Comment by xxczaki** [comment]
fixed in https://github.com/elcalc/elcalc/releases/tag/5.0-rc.1
