### ISSUE TITLE
Multiple decimal points allowed

### ISSUE THREAD

**Issue by flurmbo** [elcalc/elcalc#9]
**Desktop (please complete the following information):**
 - OS: Windows 7
 - elcalc version: 5.0.0-rc.2

**Describe the bug**
It looks like you can add multiple decimal points to a number using both keyboard and GUI buttons.

**To Reproduce**
For example try inputing "1.2.3"

**Expected behavior**
It should not let you enter the second decimal point

**Comment by xxczaki** [comment]
Thanks for the bug report, I will try to fix it soon. However, I will also add the Hacktoberfest label, so that others can fix the bug quicker 😄

**Comment by MikeM711** [comment]
You're a wizard xxczaki, I come from the Hacktoberfest label

Just submitted a pull request for this issue elcalc/elcalc#10

This is my first legit pull request for an issue, hope it looks OK!
